### ISSUE TITLE
Crack_example does not work 

### ISSUE THREAD

**Issue by romero-patrick** [petrobras/ross#1017]
Good morning!
I tried to use the crack_example function but the following error occurs

No such file or directory: '/usr/local/lib/python3.10/dist-packages/tools/data/PAPADOPOULOS.csv'

I used other functions from the defects class but this error only occurs when I use the crack function.

Thank you.

**Comment by ViniciusTxc3** [comment]
@romero-patrick currently to run the _"defects"_ class (in the future it will be called _"malfunctions"_), it needs to be run on your machine with the ross clone. Because in Jupyter or Colab, these folders are not being assigned.

![image](https://github.com/petrobras/ross/assets/42445116/76c6d63d-e4e8-45ad-a3db-8ea225a2584c)


@raphaeltimbo might know another solution.

**Comment by raphaeltimbo** [comment]
We can add the file to the package distribution. This way, after a pip install the function will run without errors.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ViniciusTxc3** [comment]
@raphaeltimbo @romero-patrick We have added the necessary files for this type of testing in PR #1038.
