### ISSUE TITLE
Crack model does not work for depth_ratio>0.5

### ISSUE THREAD

**Issue by ipereiraumich** [petrobras/ross#1055]
The transverse crack example crashes when a depth_ratio>0.5 is used. Below, you can find the error displayed when I run the script. Both Gasch and Mayes models present the same issue.
![image](https://github.com/petrobras/ross/assets/112128297/e434f3c0-1ff0-4099-9bed-6a0bf9f586bb)

**Comment by jguarato** [comment]
Hi @ipereiraumich!

The implemented approach in ROSS is based on Linear Fracture Mechanics. For cracks deeper than 50% of diameter, this approach has a singularity and cannot be used. This is discussed in [Papadopoulos (2004)](https://doi.org/10.1016/j.jsv.2003.12.023) and in [Cavalini Junior (2013)](https://repositorio.ufu.br/handle/123456789/14730).

I will incorporate error handling to trigger an alert when someone tries to set `depth_ratio > 0.5`, because these values are not compatible with the current approach.
